services:
  
  database:
    image: postgres:17

    restart: always
    container_name: learnhub_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: g8keeper
      POSTGRES_DB: learnhub_db
    ports:
      - "5433:5432"
    volumes:
      - learnhub_data:/var/lib/postgresql/data
volumes:
  learnhub_data:

  #docker compose up --build